package Test::WWW::Selenium::Manual;

=head1 NAME

Test::WWW::Selenium::Manual - Testing with Selenium

=head1 RUNNING SELENIUM TESTS

This section describes setting up and running Selenium tests on the command
line.

=head1 EXAMPLES

Basic setup

    # Start your web server on localhost (port 5000)
    # This is the web application you are going to test
    plackup -p 5000 # if you are using plack

    # Start the Selenium server
    java -jar selenium-server.jar -port 4444 -trustAllSSLCertificates -browserSessionReuse

    # Run your tests against localhost (port 5000)
    prove -lrv t/test.t


Headless server setup

    # Start Xvfb so you can run a web browser without X Windows
    Xvfb :99

    # Start the Selenium server
    DISPLAY=:99 java -jar selenium-server.jar -port 4444 -trustAllSSLCertificates -browserSessionReuse

    # Run your tests: 
    prove -lrv t/test.t


Run Selenium tests against a remote website

    SELENIUM_BROWSER_URL=http://example.com prove -lrv t/test.t


Run tests against a remote Selenium server

    # Start the Selenium server on the remote host (lets say 99.99.99.99).  
    # Then run your tests locally like this:
    SELENIUM_HOST=99.99.99.99 prove -lrv t/test.t


Running tests slowly

    # Test fly by too fast sometimes.  This slows things down.  It basically
    # calls sleep after every call to the Selenium server
    SELENIUM_SLEEP=1 prove -lrv t/test.t



=head1 SEE ALSO 

The ENVIRONMENT VARIABLES section of Test::WWW::Selenium documentation.  

The command line options for the selenium server

    java -jar selenium-server.jar -h


=cut
